### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by yaoqinchuan** [ShayanPersonal/Kaggle-Passenger-Screening-Challenge-Solution#2]
I use a computer with  1080ti and 32GB RAM ,It can not work ....

**Comment by ShayanPersonal** [comment]
If it's a Python error and not a Pytorch error then it's probably because the part of the code that loads in the dataset into memory is not optimized. You can get around this by increasing your computer's swap space through your operating system or modifying the dataloader to load in the dataset during training one batch at a time from the hard drive rather than loading in the whole dataset into RAM.

You could also save a lot of memory by loading the dataset in as half tensors (if I remember correctly the dataset uses 16-bit pixels), but when I wrote this code Pytorch had some bugs with half tensors and I don't know if they've gotten around to fixing it.

**Comment by yaoqinchuan** [comment]
thanks for your kind reply ,I change num_workers=0 in dataloader ,It works pretty well !!!
