### ISSUE TITLE
why 661 instead of 660

### ISSUE THREAD

**Issue by connorchen** [ShayanPersonal/Kaggle-Passenger-Screening-Challenge-Solution#3]
hi @ShayanPersonal 
why expand width by 1 pixel , change load image width from  660 to 661

**Comment by ShayanPersonal** [comment]
Hi Connor,
It's because of a bug in the torchsample library. In the aps files the participant's feet touch the edge of the scan. If you rotate with torchsample without padding it causes a weird smearing effect where the feet are (lines 108 through 112 in main.py). So when I load in the files I add a line of padding under the feet so that the smearing doesn't occur (line 278).

**Comment by connorchen** [comment]
@ShayanPersonal 
thanks for your explanation
